/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gamesdb;

import bo.Game;
import bo.Sale;
import dao.GameHandler;
import dao.SaleHandler;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import utils.GlobalData;

/**
 *
 * @author stephenbadeaux
 */
public class FrmAddSale extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAddSale
     */
    private void populateSale(){
        List<Sale> sales = new SaleHandler().getSales();
        ComboBoxModel cbxModel = new DefaultComboBoxModel(sales.toArray());
        cbxRegion.setModel(cbxModel);
    }
    private void populateRegions(){
        cbxRegion.removeAllItems();
        cbxRegion.addItem("Asia");
        cbxRegion.addItem("Australia");
        cbxRegion.addItem("Europe");
        cbxRegion.addItem("Japan");
        cbxRegion.addItem("North America");
    }
    private void populateGames(){
        List<Game> games = new GameHandler().loadGames("");
        ComboBoxModel cbxModel = new DefaultComboBoxModel(games.toArray());
        cbxGame.setModel(cbxModel);
    }
    public FrmAddSale() {
        initComponents();
        populateSale();
        populateRegions();
        populateGames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLDate = new javax.swing.JLabel();
        JLRegion = new javax.swing.JLabel();
        JLGame = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        cbxGame = new javax.swing.JComboBox<>();
        cbxRegion = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle("Add Sale");

        JLDate.setText("Date");

        JLRegion.setText("Region");

        JLGame.setText("Game");

        txtDate.setText("YYYYMMDD");

        cbxGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGameActionPerformed(evt);
            }
        });

        cbxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLDate)
                            .addComponent(JLRegion))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLGame)
                                .addGap(53, 53, 53)
                                .addComponent(cbxGame, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLGame)
                    .addComponent(cbxGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLRegion)
                    .addComponent(cbxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Get input values
        int saleDate = Integer.parseInt(txtDate.getText());
        String sRegion = cbxRegion.getSelectedItem().toString();
        int stfId = GlobalData.stf.getstfId();
        int ret = new SaleHandler().addSale(saleDate, sRegion, stfId);
        if (ret == -1){
            JOptionPane.showMessageDialog(this, "Failed to add Sale");
        }else{
            JOptionPane.showMessageDialog(this, "Sale added Successfully!");
            //Clear the form
            txtDate.setText("YYYYMMDD");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbxGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLDate;
    private javax.swing.JLabel JLGame;
    private javax.swing.JLabel JLRegion;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cbxGame;
    private javax.swing.JComboBox<String> cbxRegion;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
